import { AuthProvider } from "./Provider";
import "./global.css";
import Navbar from "./Components/Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className="relative font-DM">
        <div className="fixed inset-0 bg-hero-pattern opacity-70 bg-cover bg-center -z-10"></div>
        <div className="fixed inset-0 backdrop-blur-lg -z-10"></div>{" "}
        <AuthProvider>
          <Navbar />
          <main className="relative z-0">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
